apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps-infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-helm-repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: kubernetes
  path: ../applications/infrastructure
  prune: true
  validation: client
