apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps-helm-repos
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: control-plane
  path: ./applications/helm-repositories
  prune: true
  validation: client
